version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: axon
    main: ./cmd/axon
    binary: axon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: axon
    name_template: "axon_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true

release:
  github:
    owner: atakang7
    name: axon
  draft: false
  prerelease: auto
  mode: append
